# Generated by Django 4.2.9 on 2025-08-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapydServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name, e.g., Production Node', max_length=100)),
                ('host', models.CharField(help_text='Hostname or IP, e.g., 159.223.85.244 or localhost', max_length=255)),
                ('port', models.PositiveIntegerField(default=6800)),
                ('is_active', models.BooleanField(default=True)),
                ('use_https', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scrapyd_server',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
