# Generated by Django 4.2.9 on 2025-08-06 12:08

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('item', models.CharField(choices=[('url_list', 'URL List'), ('title', 'Title'), ('body', 'Body'), ('description', 'Description'), ('images', 'Images'), ('authors', 'Authors'), ('published_at', 'Published At'), ('language', 'Language')], default='url_list', max_length=20)),
                ('method', models.CharField(choices=[('css', 'CSS'), ('xpath', 'XPath'), ('regex', 'Regex')], default='css', max_length=20)),
            ],
            options={
                'db_table': 'news_article_selector',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticleAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'news_article_author',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(db_index=True)),
            ],
            options={
                'db_table': 'news_article_image',
                'ordering': ['image_url'],
            },
        ),
        migrations.CreateModel(
            name='NewsPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('news_scope', models.CharField(choices=[('national', 'National'), ('international', 'International'), ('regional', 'Regional')], default='national', max_length=20)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'News Portal',
                'verbose_name_plural': 'News Portals',
                'db_table': 'news_portal',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScraperConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('custom_settings', models.JSONField(default=dict)),
                ('item_selector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraper_configs', to='common.itemselector')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraper_configs', to='common.newsportal')),
            ],
            options={
                'db_table': 'news_scraper_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsPortalSeedUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(unique=True)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_urls', to='common.newsportal')),
            ],
            options={
                'db_table': 'news_portal_seed_url',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticleRawUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_urls', to='common.newsportal')),
            ],
            options={
                'db_table': 'news_article_url_raw',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticleCleanUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('article_url_raw', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.newsarticlerawurl')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clean_urls', to='common.newsportal')),
            ],
            options={
                'db_table': 'news_article_url_clean',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('body', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('article_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.newsarticlecleanurl')),
                ('authors', models.ManyToManyField(blank=True, to='common.newsarticleauthor')),
                ('images', models.ManyToManyField(blank=True, to='common.newsarticleimage')),
            ],
            options={
                'db_table': 'news_article',
                'ordering': ['-published_at'],
            },
        ),
        migrations.AddField(
            model_name='itemselector',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_selectors', to='common.newsportal'),
        ),
        migrations.CreateModel(
            name='CrawlerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('custom_settings', models.JSONField(default=dict)),
                ('item_selector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawler_configs', to='common.itemselector')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawler_configs', to='common.newsportal')),
            ],
            options={
                'db_table': 'news_crawler_config',
                'ordering': ['-created_at'],
            },
        ),
    ]
