# Generated by Django 4.2.9 on 2025-08-07 02:12

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_itemselector_newsarticleauthor_newsarticleimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsportal',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='ID', max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='CrawlerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scrapyd_job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.DurationField(blank=True, null=True)),
                ('crawler_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='common.crawlerconfig')),
            ],
            options={
                'db_table': 'news_crawler_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlerScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cron_expression', models.CharField(help_text="Cron expression (e.g., '0 0 * * *' for daily at midnight)", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('crawler_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='common.crawlerconfig')),
            ],
            options={
                'db_table': 'news_crawler_scheduled_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
